VAD_AUTH_TOKEN = "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"
PORT = 8000
HOST = "10.0.2.155"
DEFAULT_LANGUAGE = "english"
DEFAULT_PROCESSING_STRATEGY = "silence_anywhere"
DEFAULT_CHUNK_LENGTH_SECONDS = 2
DEFAULT_CHUNK_OFFSET_SECONDS = 0.1